import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import Navbar from '@/components/Mixins/Navbar/Navbar';
import Footer from '@/components/Mixins/Footer';
import Providers from '@/components/Common/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tiba Tiba Store',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body
        className={cn(inter.className, 'relative h-full font-sans antialiased')}
      >
        <main className="relative flex flex-col min-h-screen">
          <Providers>
            <Navbar />

            <Toaster />

            <div className="flex-1 flex-grow">{children}</div>

            <Footer />
          </Providers>
        </main>
      </body>
    </html>
  );
}
